<?php
//1
 //$a = 4;
 //$s = pow($a,2);
 //echo $s; 

//3
//$a = 3;
//$b = 3;
 //echo ($b * $a);
  //$s = 2
 //echo ($p = 2 * ($a+$b)); 

// $p = 3.14;
// $d = 76;
// echo($p*$d);

//  $a = 2;

//  $v = pow($a,3);

//  $s = 6 * pow($a,2);

//  echo "v:".$v. "s:".$s;

// $a = 2;
// $b = 8;
// $c = 5;
// echo($a*$b*$c);
// $s = 2*($a*$b+$b*$c+$a*$c);

//  $r = 3;
// $p = 2;
// $l= 2*$p*$r;
// echo ($l= 2*$p*$r );

// $a = 2;
// $b = 3;
//  $v = sqrt($a * $b);
// echo $v;

//$a = 46 ; 
//$c = $a % 10;
//$p = $c / 10;
//$q = $a % 100 - $c ;
//$v = $q / 10;
//echo $p + $v ;


//$a = 256;
//$b = $a % 10;
//$c = $a % 100 - $c ;
//$v = $q / 10;
//$n = $a % 1000 - $c - $q;

//echo $n . '<br>' $q . '<br>' . $p ;



//$a = 10;

//$b = 20;

//$L = $a + $b;

//$S = $a * $b;

//$K = pow($a,2);
//$V = pow($b,2);
//echo "L:".$L. "S:".$S."$K:".$K."V:".$V;




//$M = 1000;
//$F = 2000;
//echo ($F/$M);

//$a = 1024;
//$b = 24;

//$l = $a / $b;
//echo $l;



//$a =  10;

//$b = 2;
//$l = $a / $b;
//echo $l;


//$a = 20;
//$b = 10;
//$l = $a / $b;
//echo $l;


//$a = 50;
//$b = 30;
//$l = $a + $b;
//echo $l;

//$a = 899;
//$b = 100;
//$n = $a + $b;
//echo $n;


//$a = 8.99;
//$b = 100;
//$n = $a + $b;
//echo ($a);

//$a = 10;
//echo ($a);

//$a = 7;
//if ($a%2 == 0) {//
    //echo "u juft";
//else {

    //echo "toq";
//}
//$a = 2;

//echo  $a;


//$a = 17;
//$b = 3;
//echo  "$a:".$a. "$b:".$b;


//$a = 8;
//if ($a%2 == 0) {
    //echo "u juft";
//}else 
//echo "toq";


//$a = 4;
//if ($a > 0){
    //echo $a + 1;
//}else {
    //echo $a;
//}







//$a = 1;
//if ($a ==1 ) {
//  echo "Dushanba";
//}else {
//    echo $a, "Seshanba";
//}


//$a = 1;
//if ($a ==1  ) {
// echo "Yomon";
//}else 
    //echo $a, "Alo";

    //$a = 2;
//if ($a ==2 ) {
 // echo "Qish";
//}else 
//echo $a, "Kuz"

//$a = 3;
//$b = 3;
//$n = 6;

//switch ($n) {
    //case 1:
      //echo "Qoshsh";
      //break;
    //case 2:
      //echo "Ayrish";
      //break;
    //case 3:
      //echo "Kopaytirish";
      //break;
    //default:
      //echo "Bolish";
      //case 5:
        //echo "Birlashtirish";

        //case 6:
            //echo "Kirkish";

  //}

//$a = 3;
//$b = 3;
//$n = 2;

//switch ($n) {
    //case 1:
    //echo "desimetr";
    //  //break;
    //case 2:
     //echo "kilometr";
      //break;
   // case 3:
      //echo "metr";
      //break;
    //case 4:
      //echo "milimetr";
      //case 5:
      // // echo "santimetr";
      //}


    
//$d = 31;
//$m = 1;

//switch ($m) {
    //case 1:
        //echo " $d-YANVAR";
        //break;
    //case 2:
        //echo "$d-fevral";
        //break;
    //case 3:
        //echo "$d-mart";
        //break;
    //case 4:
        //echo "$d-aprel";
        //break;
    //case 5:
       // echo "$d-may";
        //break;
    //case 6:
       // echo "$d-iyun";
        //break;
    //case 7:
        //echo "$d-iyul";
        //break;
    //case 8:
       // echo "$d-avgust";
        //break;
    //case 9:
        //echo "$d-sentabr";
        //break;
    //case 10:
        //echo "$d-oktabr";
        //break;
    //case 11:
        //echo "$d-noyabr";
        //break;
    //case 12:
        //echo "$d-dekabr";
        //break;
    //default:
        //echo "";
//}





//$d = 5;
//$m = 1;

//switch ($m) {

    //case 1:
        //break;
    //case 2:
       //echo "$d-fevral";
        //break;
    //case 3:
        //echo "$d-mart";
        //break;
    //case 4:
       // echo "$d-aprel";
        //break;
    //case 5:
       // echo "$d-may";
        //break;
   // case 6:
       // echo "$d-iyun";
        //break;
   //case 7:
        //echo "$d-iyul";
        //break;
   // case 8:
       // echo "$d-avgust";
        //break;
    //case 9:
        //echo "$d-sentabr";
        //break;
    //case 10:
        //echo "$d-oktabr";
        //break;
   // case 11:
       //echo "$d-noyabr";
        //break;
    //case 12:
        //echo "$d-dekabr";
        //break;
    //default:
        //echo "";
//}


//$a = 10;
//$b = 20;
//echo ($a*$b);

//$a = 200;
//$b = 10;
//$sonlar = [];
//for($i = 0; $i <= $b; $i++){

//$sonlar[] = $i;

//}
//$n = $a  * $i;
//print_r($sonlar);
//echo $n;


//$a = 200;
//$b = 2;

//$sonlar = [];

//for ($i = 1.2; $i  <= $b; $i+ 0.2) {
//$sonlar[] = $i;
//}
//$n = $a *$i; 
//print_r($sonlar);
//echo $n;


///$a = 5;

///for ($i = $b; $i <= $a; $i++) {
 ///echo $i. "<br>";
///}
///echo 2*2+3*3+4*4+5*5+6*6;



$n = 5;

for ($i = 1; $i <= $n; $i++) {
    echo $i. "<br>";
}


?>



